<!DOCTYPE html>
<html lang="id">
   <head>
      <meta charset="utf-8">
      <title>Daftar Penawaran (offer/ijab/ʿījāb/الإيجاب/añaŋ/ꦲꦚꦁ) – Loːts 100₂.C.a.111₂.101₂</title>
      <meta name="description" content="aplikasi untuk mengirim rekaman penawaran/ʿījāb/الإيجاب/offer/añaŋ/ꦲꦚꦁ/aanbod pada tabel di bawah, bisa diunduh di Play Store: https://play.google.com/store/apps/details?id=id.menawar.menerima, kode sumbernya bisa diakses di repository (gudang) github berikut: https://github.com/dawud-tan/penawaran. Kode sumber untuk server (peladen) penerima penawaran dari aplikasi Akta Bawah Tangan bisa diakses di gudang github berikut: https://github.com/dawud-tan/penerimaan">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
      <link rel="preconnect" href="https://www.googletagmanager.com/" crossorigin>
      <link rel="dns-prefetch" href="https://www.googletagmanager.com/">
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-2Y02NDHGW7"></script>
      <script>window.dataLayer = window.dataLayer || []; window.dataLayer.push("js", new Date()); window.dataLayer.push("config", "G-2Y02NDHGW7");</script>
      <link rel="apple-touch-icon-precomposed" sizes="57x57" href="apple-touch-icon-57x57.png" />
      <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114.png" />
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72.png" />
      <link rel="apple-touch-icon-precomposed" sizes="144x144" href="apple-touch-icon-144x144.png" />
      <link rel="apple-touch-icon-precomposed" sizes="60x60" href="apple-touch-icon-60x60.png" />
      <link rel="apple-touch-icon-precomposed" sizes="120x120" href="apple-touch-icon-120x120.png" />
      <link rel="apple-touch-icon-precomposed" sizes="76x76" href="apple-touch-icon-76x76.png" />
      <link rel="apple-touch-icon-precomposed" sizes="152x152" href="apple-touch-icon-152x152.png" />
      <link rel="icon" type="image/png" href="favicon-196x196.png" sizes="196x196" />
      <link rel="icon" type="image/png" href="favicon-96x96.png" sizes="96x96" />
      <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
      <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />
      <link rel="icon" type="image/png" href="favicon-128.png" sizes="128x128" />
      <meta name="application-name" content="&nbsp;"/>
      <meta name="msapplication-TileColor" content="#FFFFFF" />
      <meta name="msapplication-TileImage" content="mstile-144x144.png" />
      <meta name="msapplication-square70x70logo" content="mstile-70x70.png" />
      <meta name="msapplication-square150x150logo" content="mstile-150x150.png" />
      <meta name="msapplication-wide310x150logo" content="mstile-310x150.png" />
      <meta name="msapplication-square310x310logo" content="mstile-310x310.png" />
      <meta property="og:url" content="http://akta-bawah-tangan.ip-dynamic.com/">
      <meta property="og:site_name" content="Dwimal">
      <meta property="og:type" content="website">
      <meta property="og:locale" content="id_ID">
      <meta property="og:author" content="Dawud Tan">
      <meta property="og:title" content="Daftar Penawaran (offer/ijab/ʿījāb/الإيجاب/añaŋ/ꦲꦚꦁ) – Loːts 100₂.C.a.111₂.101₂">
      <meta property="og:description" content="aplikasi untuk mengirim rekaman penawaran/ʿījāb/الإيجاب/offer/añaŋ/ꦲꦚꦁ/aanbod pada tabel di bawah, bisa diunduh di Play Store: https://play.google.com/store/apps/details?id=id.menawar.menerima, kode sumbernya bisa diakses di repository (gudang) github berikut: https://github.com/dawud-tan/penawaran. Kode sumber untuk server (peladen) penerima penawaran dari aplikasi Akta Bawah Tangan bisa diakses di gudang github berikut: https://github.com/dawud-tan/penerimaan">
      <meta property="fb:admins" content="1656390643"/>
      <meta property="fb:app_id" content="1034592877036368"/>
      <meta name="twitter:card" content="summary">
      <meta name="twitter:site" content="@dawud_tan">
      <meta name="twitter:creator" content="@dawud_tan">
      <meta name="twitter:title" content="Daftar Penawaran (offer/ijab/ʿījāb/الإيجاب/añaŋ/ꦲꦚꦁ) – Loːts 100₂.C.a.111₂.101₂">
      <meta name="twitter:description" content="aplikasi untuk mengirim rekaman penawaran/ʿījāb/الإيجاب/offer/añaŋ/ꦲꦚꦁ/aanbod pada tabel di bawah, bisa diunduh di Play Store: https://play.google.com/store/apps/details?id=id.menawar.menerima, kode sumbernya bisa diakses di repository (gudang) github berikut: https://github.com/dawud-tan/penawaran. Kode sumber untuk server (peladen) penerima penawaran dari aplikasi Akta Bawah Tangan bisa diakses di gudang github berikut: https://github.com/dawud-tan/penerimaan">
      <meta name="google-site-verification" content="w4NicX1RLeYJl6cvAriG8BDfOCl3bhJ4YtVkh_W2Lb8">
      <meta name="msvalidate.01" content="6BD2880613950F8B776E86E67A6307DE">
      <meta name="yandex-verification" content="f75843aaa72c79a7" />
      <meta http-equiv="content-language" content="id">
      <link rel="canonical" href="http://akta-bawah-tangan.ip-dynamic.com/">
      <link rel="alternate" hreflang="id-Latn-ID" href="http://akta-bawah-tangan.ip-dynamic.com/">
      <link rel="alternate" hreflang="x-default" href="http://akta-bawah-tangan.ip-dynamic.com/">
      <link rel="preconnect" href="https://mscomajax.vo.msecnd.net/" crossorigin>
      <link rel="dns-prefetch" href="https://mscomajax.vo.msecnd.net/">
      <link rel="preload" href="https://mscomajax.vo.msecnd.net/ajax/bootstrap/3.4.1/css/bootstrap.min.css" as="style" type="text/css" crossorigin>
      <link rel="preload" href="/fonts/CharisSIL-Regular.woff2" as="font" type="font/woff2" crossorigin>
      <link rel="preload" href="/fonts/CharisSIL-Italic.woff2" as="font" type="font/woff2" crossorigin>
      <link rel="preload" href="/fonts/ScheherazadeNew-Regular.woff2" as="font" type="font/woff2" crossorigin>
      <link rel="preload" href="/fonts/NgayogyanJejeg-Regular.woff2" as="font" type="font/woff2" crossorigin>
      <link rel="preload" href="https://mscomajax.vo.msecnd.net/ajax/jQuery/jquery-2.2.4.min.js" as="script" type="text/javascript" crossorigin>
      <link rel="preload" href="https://mscomajax.vo.msecnd.net/ajax/bootstrap/3.4.1/bootstrap.min.js" as="script" type="text/javascript" crossorigin>
      <link rel="stylesheet" href="https://mscomajax.vo.msecnd.net/ajax/bootstrap/3.4.1/css/bootstrap.min.css" crossorigin="anonymous">
      <style>
		@font-face {
			font-display: swap;
			font-family: "Charis SIL";
			font-style: normal;
			font-weight: normal;
			src: url(/fonts/CharisSIL-Regular.woff2) format("woff2"), url(/fonts/CharisSIL-Regular.woff) format("woff"), url(/fonts/CharisSIL-Regular.ttf) format("truetype");
			unicode-range: U+0020, U+0023, U+0028-0029, U+002B-003A, U+003D, U+003F, U+0041-005A, U+0061-007A, U+00E5, U+02E2, U+1D43, U+1D48-1D49, U+1D4D, U+1D4F, U+1D52, U+1D56-1D57, U+207F;
		}

		@font-face {
			font-display: swap;
			font-family: "Charis SIL";
			font-style: italic;
			font-weight: normal;
			src: url(/fonts/CharisSIL-Italic.woff2) format("woff2"), url(/fonts/CharisSIL-Italic.woff) format("woff"), url(/fonts/CharisSIL-Italic.ttf) format("truetype");
			unicode-range: U+0020, U+002C, U+002E, U+0031-0032, U+003A, U+004D, U+0061-0062, U+0064-0076, U+0079, U+00E5, U+00E9, U+00F1, U+0101, U+0115, U+012B, U+014B, U+02BF, U+1E0D, U+1E6D;
		}

		@font-face {
			font-display: swap;
			font-family: "Scheherazade New";
			font-style: normal;
			font-weight: normal;
			src: url(/fonts/ScheherazadeNew-Regular.woff2) format("woff2"), url(/fonts/ScheherazadeNew-Regular.woff) format("woff"), url(/fonts/ScheherazadeNew-Regular.ttf) format("truetype");
			unicode-range: U+0625, U+0627-062A, U+062C, U+062F, U+0633, U+0635, U+0639-063A, U+0642-0646, U+0648, U+064A, U+064E-0650, U+0652-0653, U+0661-0662, U+069F-06A0, U+06A4, U+06AE, U+06D1, U+08AE;
		}

		@font-face {
			font-display: swap;
			font-family: "nyk Ngayogyan Jejeg";
			font-style: normal;
			font-weight: normal;
			src: url(/fonts/NgayogyanJejeg-Regular.woff2) format('woff2'), url(/fonts/NgayogyanJejeg-Regular.woff) format('woff'), url(/fonts/NgayogyanJejeg-Regular.ttf) format('truetype');
			unicode-range: U+A981, U+A98F, U+A992, U+A997, U+A99A-A99B, U+A99D, U+A9A0, U+A9A4-A9A5, U+A9A7, U+A9A9, U+A9AD, U+A9B1-A9B2, U+A9B6, U+A9B8, U+A9BA, U+A9BC, U+A9C0, U+A9C7, U+A9C9, U+A9CB, U+A9D1-A9D2;
		}

		html {
			font-size: 2.4vw;
		}

		@media all and (min-width:1000px) {
			html {
				font-size: 24px;
			}
		}

		@media all and (max-width:520px) {
			html {
				font-size: 18px;
			}
		}

		body {
			font-family: "Charis SIL", serif;
			line-height: 1.5;
			font-size: 0.9rem;
			margin-left: auto;
			margin-right: auto;
			padding-bottom: 65px;
			width: 100%;
			max-width: 1000px;
			min-height: 100%;
			position: relative;
			z-index: -10000;
			-webkit-font-smoothing: subpixel-antialiased;
			padding-top: 50px;
		}

		.footer {
			display: block;
			position: fixed;
			left: 0;
			right: 0;
			z-index: 1030;
			bottom: 0;
			width: 100%;
			/* Set the fixed height of the footer here */
			height: 60px;
			line-height: 60px;
			/* Vertically center the text there */
			background-color: #f5f5f5;
			overflow-x: auto;
			white-space: nowrap;
			-webkit-overflow-scrolling: touch;
		}

		.footer>.container {
			margin-left: auto;
			margin-right: auto;
			max-width: 1000px;
		}

		div#isi {
			padding: 3rem 0 65px 0;
			margin-left: 7.25rem;
			margin-right: 7.25rem;
		}

		@media all and (max-width:520px) {
			div#isi {
				margin-left: 1.5rem;
				margin-right: 1.5rem;
				padding: 0 0 65px 0;
			}
		}

		 :lang(ar),
		 :lang(jv-Arab-ID) {
			font-family: "Scheherazade New", serif;
		}

		 :lang(jv-Java) {
			font-family: "nyk Ngayogyan Jejeg", serif;
		}

		.bg-dark {
			background-color: #3b8dbd !important;
		}

		.navbar-default .navbar-nav > .active > a,
		.navbar-default .navbar-nav > .active > a:focus,
		.navbar-default .navbar-nav > .active > a:hover {
			color: #296283;
			background-color: #2f7096;
		}

		p {
			margin-bottom: 12pt;
		}

		.align-middle {
			 vertical-align: middle !important
		}

		@-ms-viewport {
			width: device-width;
		}

		@-o-viewport {
			width: device-width;
		}

		@viewport {
			width: device-width;
		}

		@-moz-document url-prefix() {
			fieldset {
				display: table-cell;
			}
		}
      </style>
   </head>
   <body>
      <nav class="navbar navbar-default navbar-fixed-top bg-dark">
         <div class="container">
            <div class="navbar-header">
               <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-expanded="false" aria-controls="navbar">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="/"><img class="img-responsive" src="/images/logo.webp" width="173" height="20" alt="logo Loːts 100₂.C.a.111₂.101₂"></a>
            </div>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
               <ul class="nav navbar-nav">
                  <li class="active">
                     <a href="/">Daftar Penawaran <span class="sr-only">(current)</span></a>
                  </li>
                  <li>
                     <a href="/perikatan.html">Perikatan Daring (<em>online</em>)</a>
                  </li>
                  <li>
                     <a href="/kok-gs1-pun-drummond-group-belum-ada-sikap-soal-ancaman-prosesor-quantum.html">Sikap GS1 soal Prosesor Quantum?</a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
      <div id="isi">
         <p>aplikasi untuk mengirim rekaman penawaran/<em><span lang="ar-Latn-ID">ʿījāb</span></em>/<span lang="ar-Arab-ID">الإيجاب</span>/<em><span lang="en-Latn-US">offer</span></em>/<em><span lang="jv-Latn-ID">añaŋ</span></em>/<span lang="jv-Java-ID">ꦲꦚꦁ</span>/<em><span lang="nl-Latn-NL">aanbod</span></em> pada tabel di bawah, bisa diunduh di <a rel="external nofollow" href="https://play.google.com/store/apps/details?id=id.menawar.menerima&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1">Play Store</a>, kode sumbernya bisa diakses di <em><span lang="en-Latn-US">repository</span></em> (gudang) github berikut: <a rel="external nofollow" target="_blank" href="https://github.com/dawud-tan/penawaran">penawaran</a></p>
         <p>kode sumber untuk <em><span lang="en-Latn-US">server</span></em> (peladen) penerima penawaran dari aplikasi Akta Bawah Tangan bisa diakses di gudang github berikut: <a rel="external nofollow" target="_blank" href="https://github.com/dawud-tan/penerimaan">aplikasi penerimaan</a></p>
         <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-condensed">
               <thead>
                  <tr>
                     <th rowspan="2" class="align-middle text-center">#</th>
                     <th rowspan="2" class="align-middle text-center">penawaran (<em>offer</em>)</th>
                     <th colspan="4" class="align-middle">Tanda Tangan Digital SHA512withRSA</th>
                  </tr>
                  <tr>
                     <th class="align-middle">Sisa Bagi emsaᵉᵏˢᵖᵒⁿᵉⁿ ᵖᵉⁿᵃⁿᵈᵃᵗᵃⁿᵍᵃⁿᵃⁿ mod modulus</th>
                     <th class="align-middle">Waktu Penandatanganan</th>
                     <th class="align-middle">Base64 hash SHA-512nya redaksi penawaran</th>
                     <th class="align-middle">Alamat IP Pembeli</th>
                  </tr>
               </thead>
               <tbody>
                  <tr>
                     <td>1</td>
                     <td lang="jv-Latn-ID"><em>munḍut baṭik pisan bali 12 kåḍi kintun tĕŋ guḍaŋ béñjiŋ</em></td>
                     <td>1.416.113.756.197.991.631.384.059.083.151.104.375.758.119.392.366.862.128.722.355.151.983.986.467.020.830.675.029.476.418.281.443.266.731.172.992.101.238.447.010.115.039.828.048.047.907.851.542.903.841.888.126.326.114.112.174.677.146.141.168.847.494.703.724.902.137.086.180.993.455.596.385.052.497.343.747.520.978.972.315.599.759.332.746.731.982.961.067.081.125.573.786.523.232.976.865.992.514.940.627.590.555.515.875.523.525.211.165.181.194.809.739.147.206.830.634.606.117.958.764.931.076.110.139.863.394.482.057.120.824.164.444.097.951.087.581.696.638.166.939.300.317.276.984.149.529.015.032.932.600.831.509.321.751.288.133.293.701.349.667.901.373.945.519.409.863.856.818.335.921.142.877.343.303.455.068.319.410.272.522.233.840.782.311.616.455.574.424.875.257.999.994.977.830.939.477.026.804.135.167.480.064.984.293.775 (616 digit)</td>
                     <td>26 Mei 2021 20.21.39</td>
                     <td>vVPLzNEmO+icsl4tlyCWlqAP4WHZW6+BitEzDeb745EGDaSJI68fTiQyvTANnBNLuIie0nCf7A9JNqvcN5I+dA==</td>
                     <td>182.2.70.190</td>
                  </tr>
                  <tr>
                     <td>2</td>
                     <td lang="jv-Java-ID">꧋ꦩꦸꦤ꧀ꦝꦸꦠ꧀ꦧꦛꦶꦏ꧀ꦥꦶꦱꦤ꧀ꦧꦭꦶ꧇꧑꧒꧇ꦏꦝꦶꦏꦶꦤ꧀ꦠꦸꦤ꧀ꦠꦼꦁꦒꦸꦝꦁꦧꦺꦚ꧀ꦗꦶꦁ꧉</td>
                     <td>9.326.801.998.838.273.006.960.112.565.244.536.919.937.124.449.216.164.060.888.175.023.177.018.768.354.398.989.568.464.054.370.499.283.556.822.443.680.503.209.329.782.373.529.177.959.799.269.758.369.989.056.422.841.206.339.322.158.952.958.846.628.469.205.361.193.638.977.622.385.020.444.287.502.104.824.199.178.569.588.073.877.636.965.804.143.774.109.246.004.818.234.214.329.184.541.236.842.498.072.043.229.202.725.056.510.329.605.904.736.255.354.959.277.677.583.391.919.443.485.349.425.377.969.694.004.632.551.769.500.674.782.066.663.723.644.682.954.176.350.279.192.585.245.764.796.064.355.893.074.602.545.443.530.850.700.266.562.520.997.031.151.049.143.301.339.954.298.883.201.431.719.093.020.424.882.565.399.681.029.196.617.789.361.145.592.502.390.490.314.459.595.089.394.263.022.273.435.484.445.561.211.812.075.014.753 (616 digit)</td>
                     <td>26 Mei 2021 20.23.09</td>
                     <td>f8qJn0expq6XaXxajYvFHgaZWtk6Y1DQWIeGnegpMJT3XytZt1tfAcrsceTxU25stX+ZbH3oZLVal6p3uvoxXg==</td>
                     <td>182.2.70.190</td>
                  </tr>
                  <tr>
                     <td>3</td>
                     <td style='direction:rtl; text-align: right' lang="jv-Arab-ID">مُوْنْࢮُوْةْبَاڟِيْكْڤِيْسَانْبَالِيْ١٢كَاࢮِيْكِيْنْتُوْنْتٓڠْڮُوْࢮَاڠْبَيْۑْجِيْڠْ</td>
                     <td>587.832.243.432.637.827.330.149.696.070.880.388.150.951.364.684.189.126.250.483.779.999.352.557.149.165.785.315.734.809.831.290.751.272.893.766.404.641.944.084.662.072.753.989.693.875.374.608.712.988.255.423.238.801.098.478.213.270.383.777.490.450.124.079.076.634.698.782.140.467.894.939.681.405.818.916.763.424.505.990.239.567.951.616.308.805.614.843.996.809.847.067.752.969.461.700.025.610.656.310.457.668.146.684.594.886.643.073.129.546.524.369.763.170.536.653.872.219.180.218.537.028.182.635.020.456.237.284.758.674.228.224.506.197.268.128.286.595.861.881.856.469.153.639.754.851.489.560.490.280.184.317.479.110.387.293.027.671.509.827.670.322.739.185.418.816.619.812.356.301.637.521.537.285.397.011.288.527.486.446.668.028.603.260.110.812.940.982.774.929.157.766.017.882.621.425.537.357.120.196.345.345.832.830.353 (615 digit)</td>
                     <td>26 Mei 2021 20.23.35</td>
                     <td>X5tFRcYwYdD7ptZB8d6QEWKSxJddMrF14ubdUkMzEpmQSZi1ketXQasi2DR94xSuRH92ckrE/jDTXwT5vAXHgw==</td>
                     <td>182.2.70.190</td>
                  </tr>
                  <tr>
                     <td>4</td>
                     <td><span style='direction:rtl; text-align: right' lang="ar-Arab-ID">صيغة عقد</span>, itu yang seperti apa?</td>
                     <td>6.829.301.526.835.101.184.857.828.533.422.934.663.378.636.434.616.888.041.315.361.807.913.517.313.317.273.604.455.603.001.971.492.443.700.706.697.732.529.127.041.355.542.826.445.969.728.187.012.542.107.115.220.977.269.662.777.684.769.627.221.252.337.801.689.015.058.290.856.370.678.688.769.944.407.360.821.254.894.039.876.427.849.597.224.028.533.339.500.522.144.482.350.169.841.323.725.752.623.080.804.842.115.916.392.385.071.048.732.980.337.424.269.513.837.880.931.388.510.910.346.755.638.327.793.916.601.577.195.935.441.223.457.144.631.031.514.853.608.205.404.113.981.780.492.985.198.489.130.799.355.773.608.656.759.952.221.848.743.668.069.195.627.599.795.707.216.955.071.235.039.776.508.666.276.700.241.004.846.601.937.643.614.602.190.879.769.544.235.309.599.655.489.399.483.343.058.027.247.017.382.060.064.289.915.044 (616 digit)</td>
                     <td>26 Mei 2021 20.24.21</td>
                     <td>TQ72Zu+wVZoMy6VQb4toI3Jcv5gL5a6Sg3L0CTk/4zz4CnHI/79fUxFAdI05N1OYXU2eyXOsVHeRiI2xjF+xgw==</td>
                     <td>182.2.70.190</td>
                  </tr>
                  <#list model["penawarans"] as p>
                  <tr>
                     <td>${p?counter + 4}</td>
                     <td>${p.penawaran}</td>
                     <td>${p.sisaBagi} (${p.jumlahDigit} digit)</td>
                     <td>${p.tanggal?datetime}</td>
                     <td>${p.hashnya}</td>
                     <td>${p.alamatIP}</td>
                  </tr>
                  </#list>
               </tbody>
            </table>
         </div>
         <p><time datetime="${model.datetime}"><a rel="external nofollow" href="https://www.google.co.id/maps/search/?api=1&amp;hl=id&amp;query=Jalan+Kanthil%2C+Kacangan%2C+RT.2/RW.1%2C+Kacangan%2C+Andong%2C+Boyolali%2C+Jawa+Tengah%2C+57384%2C+Indonesia&amp;query_place_id=ChIJHZHTjxQNei4RpPREdCM-aEI">Kacangan, Båyålali</a>,  ${model.waktu}</time></p>
      </div>
      <footer class="footer">
         <div class="container">
            <a rel="external nofollow" hreflang="de-Latn-DE" href="https://www.uni-goettingen.de/de/473464.html"><em><span class="text-muted"  lang="fr-Latn-FR">Méthode: par laquelle, au moyen de un nombre fini de opérations, on pourra distinguer.</span></em></a>
         </div>
      </footer>
      <script src="https://mscomajax.vo.msecnd.net/ajax/jQuery/jquery-2.2.4.min.js" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/js/vendor/jquery.min.js"><\/script>')</script>
      <script src="https://mscomajax.vo.msecnd.net/ajax/bootstrap/3.4.1/bootstrap.min.js" crossorigin="anonymous"></script>
      <script>
		/*!
		 * IE10 viewport hack for Surface/desktop Windows 8 bug
		 * Copyright 2014-2019 Twitter, Inc.
		 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
		 */
		(function() {
			'use strict';
			if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
				var msViewportStyle = document.createElement('style')
				msViewportStyle.appendChild(
					document.createTextNode(
						'@-ms-viewport{width:auto!important}'
					)
				)
				document.querySelector('head').appendChild(msViewportStyle)
			}
		})();
      </script>
   </body>
</html>